version: '3.9'
services:
  php:
    build: .
    image: php:8.0-rc-apache-buster
    volumes:
       - ./main_app:/var/www/html
    ports:
      - 8081:80
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: nameuser
      MYSQL_PASSWORD: secretpassword
      MYSQL_ROOT_PASSWORD: secretpassword2
    volumes:
      - mysql-data:/var/lib/mysql
  adminer:
    image: adminer:latest
    ports:
      - 8082:8080
volumes:
  mysql-data: